#!/bin/bash

plain='\033[0m'

red='\e[31m'
yellow='\e[33m'
gray='\e[90m'
green='\e[92m'
blue='\e[94m'
magenta='\e[95m'
cyan='\e[96m'
none='\e[0m'
# Font Size
# h6 = SMALL , h4 = AVERAGE , h3 = LARGE
# Check Root
[[ $EUID -ne 0 ]] && echo -e "${red}Error: ${plain} You must use root user to run this script!\n" && exit 1

sed -i 's/#\?AllowTcpForwarding .*/AllowTcpForwarding yes/' /etc/ssh/sshd_config && sed -i 's/#\?PasswordAuthentication .*/PasswordAuthentication yes/' /etc/ssh/sshd_config && sed -i 's/#\?Banner .*/Banner \/etc\/ssh\/ko_chit/' /etc/ssh/sshd_config && /etc/init.d/ssh restart;
echo "
<h3><font color='red'>▬▬▬▬▬▬ஜ۩۞۩ஜ▬▬▬▬▬▬
</font></h3>
<h3><font color='magenta'>--- ۩ ပရီမီယမ် ဆာဗာ ۩ ---
</font></h3>

<h3><font color='green'>--- ကိုယ်ဖြစ်ချင်တာထက်ဖြစ်သင့်ဘဲလုပ်ရတာဘဲဟန်နီ👩
</font></h3>

<h3><font color='green'>--- ပင်ပန်းတာထက်ပိုလွမ်းတာကပိုပါတယ်ဟန်နီ🐢
</font></h3>

<h3><font color='gray'>--- ۩ SERVER BY KO CHIT ۩ ---
</font></h3>

<h4><font color='cyan'>Telegram Channel >> https://t.me/kochitt
</font></h4>

<h4><font color='blue'>Telegram Channel >> https://t.me/gcpsevergoodspeed
</font></h4>

<h3><font color='red'>▬▬▬▬▬▬ஜ۩۞۩ஜ▬▬▬▬▬▬
</font></h3>" | tee /etc/ssh/ko_chit >/dev/null
useradd "chit" --shell=/bin/false -M
echo "chit:chit" | chpasswd

echo ""

echo -e "${yellow}▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬${plain}"
echo -e "${cyan}  ..######..##.....##.####.########                 ${plain}"
echo -e "${cyan}  .##....##.##.....##..##.....##...                 ${plain}"
echo -e "${cyan}  .##.......##.....##..##.....##...                 ${plain}"
echo -e "${cyan}  .##.......#########..##.....##...                 ${plain}"
echo -e "${cyan}  .##.......##.....##..##.....##...                 ${plain}"
echo -e "${cyan}  .##....##.##.....##..##.....##...                 ${plain}"
echo -e "${cyan}  ..######..##.....##.####....##...                 ${plain}"
echo -e "${yellow}▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬${plain}"
echo -e "${green}Contact me https://t.me/kochitt for more information.${plain}"
echo -e "${yellow}▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬ ${plain}"

echo -e "${cyan}i am kochit 😋 ${plain}"
